package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bonus.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public abstract class Bonus extends GameElements {
	public abstract void ApplyEffects();
}
