package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Character.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public abstract class Character extends GameElements {
	public void Moove() {
	}
	
	public abstract void Die();
}
