package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Enemy.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public class Enemy extends Character {
	public void Die() {
	}
	
}
