package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GameElements.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public class GameElements {
	public Object Shape;
	public Object Coordinate;
	public Object DisplayManagement;
}
