package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Laser.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public class Laser extends GameElements {
	public int Stacks;
	public int NbCurrentBullet;
	public static int NbMaxBullet;
	public static int minBullet;
	public int lifePoint;
}
