package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Life.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public class Life extends Bonus {
	public void ApplyEffects() {
	}
}
