package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Map.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public class Map {
	public int NbCol;
	public int NbLine;
	public GameElements elements;
}
