package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public class Player extends Character {
	public int NbLifes;
	public Shield Shield;
	public Laser Laser;
	public void Shoot() {
	}
	
	public void Die() {
	}
}
