package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Program.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public class Program {
	public Object map;
}
