package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shape.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public class Shape {
	public String ImageLink;
}
