package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ShieldBonus.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public class ShieldBonus extends Bonus {
	public int NewDuration;
	public void ApplyEffects() {
	}
	
}
