package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shield.java
//  @ Date : 12/03/2020
//  @ Author : 
//
//




public class Shield extends GameElements {
	public int MaxDuration;
	public int CurentDuration;
	public void TakeDamages() {
	}
}
